export class OnItemNumChange{
  onBuildingChange:OnBuildingChange;
  onStudentChange:OnStudentChange;
  onStudentRemove:OnStudentRemove;
  onSchoolChange:OnSchoolChange;
  onTokenChange:OnTokenChange;
  onItemNumChange:OnItemNumChange;
  id:number// 建筑id;
  pos:string// 建筑位置;
  info:Building;
  _id:number// 建筑唯一id（0表示一键收取）;
  type:number// 1看广告（单一领取黄金树）;
  _id:number// 建筑唯一id;
  _id:number// 建筑唯一id;
  locked:number// 是否加锁;
  _id:number// 建筑唯一id;
  _id:number// 建筑唯一id;
  type:number// 1：学员，2：课程，3：教员，4：特殊功能，5：自动生产;
  pos:number// 教员位置、特殊功能位置;
  num:number// 增加后的容量;
  _id:number// 建筑唯一id;
  teacherUid:number// 教员唯一id;
  skillId:number// 教员技能id;
  info:BuildingProduct;
  _id:number// 建筑唯一id;
  productUid:number// 课程唯一id;
  auto:number// 0不自动；1自动;
  auto:number;
  _id:number// 建筑唯一id;
  productUid:number// 课程唯一id;
  _id:number// 建筑唯一id;
  buildingUid:number// 被移动建筑唯一id（0建筑背包，建筑背包的课程endTime都是0）;
  productUid:number// 被移动建筑的课程唯一id（寻找buildingUid，先判断endTime，再遍历所有建筑）;
  info:BuildingProduct// 移动后生成的新课程;
  _id:number// 建筑唯一id;
  pos:number// 教员位置（从0开始）;
  teacherUid:number// 教员唯一id;
  _id:number// 建筑唯一id;
  pos:number// 教员位置（从0开始）;
  functionUid:number// 功能id;
}